crop_bed_id: 2
canbus_id: can2
port: 17652
pdm_config_files:
  1: ./config/devices/crop_bed/pdm_1.yaml
  0: ./config/devices/crop_bed/pdm_0.yaml
channel_map:
  13:
  - 12
  - 0
  20:
  - 5
  - 0
  6:
  - 19
  - 1
  18:
  - 7
  - 0
  7:
  - 18
  - 1
  4:
  - 21
  - 1
  12:
  - 13
  - 1
  14:
  - 11
  - 0
  9:
  - 16
  - 1
  11:
  - 14
  - 1
  16:
  - 9
  - 0
  5:
  - 20
  - 1
  15:
  - 10
  - 0
  17:
  - 8
  - 0
  1:
  - 24
  - 1
  8:
  - 17
  - 1
  23:
  - 2
  - 0
  2:
  - 23
  - 1
  10:
  - 15
  - 1
  21:
  - 4
  - 0
  22:
  - 3
  - 0
  3:
  - 22
  - 1
  24:
  - 1
  - 0
  19:
  - 6
  - 0
