crop_bed_id: 1
canbus_id: can1
port: 17651
pdm_config_files:
  1: ./config/devices/crop_bed/pdm_1.yaml
  0: ./config/devices/crop_bed/pdm_0.yaml
channel_map:
  11:
  - 21
  - 1
  13:
  - 23
  - 1
  2:
  - 12
  - 0
  4:
  - 14
  - 1
  5:
  - 15
  - 1
  8:
  - 18
  - 1
  9:
  - 19
  - 1
  6:
  - 16
  - 1
  12:
  - 22
  - 1
  14:
  - 24
  - 1
  7:
  - 17
  - 1
  3:
  - 13
  - 1
  1:
  - 11
  - 0
  10:
  - 20
  - 1
